version: "3.8"
# docker compose -f docker-compose-plugin-table.yaml up
services:
  groundingdino_gradio:
    build:
      dockerfile: Dockerfile.gradio

    restart: always
    image: msoo.ces.myfiinet.com:6702/groundingdino_gradio:1.0.0

    volumes:
      - /data/.cache:/root/.cache
      - ./groundingdino:/app/groundingdino
      - ./demo/gradio_app.py:/app/gradio_app.py
    # entrypoint:  ["tail", "-f", "/dev/null"]
    entrypoint:  ["python", "gradio_app.py"]
    ports:
      - "6614:7579"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 4
              capabilities: [gpu]
              device_ids: ["1"]
