version: "3.8"
# docker compose -f docker-compose-plugin-table.yaml up
services:
  groundingdino_gradio:
    build:
      dockerfile: Dockerfile.gradio

    restart: always
    image: msoo.ces.myfiinet.com:6702/groundingdino_gradio:1.0.0

    volumes:
      - /data/.cache:/root/.cache
      - ./groundingdino:/app/groundingdino
      - ./demo/gradio_app.py:/app/gradio_app.py
    # entrypoint:  ["tail", "-f", "/dev/null"]
    # entrypoint:  ["python", "gradio_app.py"]
    entrypoint: ["sh", "-c", "python setup.py build develop --user && python gradio_app.py"] # 第一次執行需要這個

    ports:
      - "6614:7579"
    env_file: ".env"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 4
              capabilities: [gpu]
              device_ids: ["1"]
